"""
scripts/build_patient_file.py

Generate 23andMe-format genome files for the 3 demo patients by writing only
the 10 target rsIDs (other lines are not needed for the demo).

Output:
  data/genomes/patient_a.txt   (PT-001 — Alex Rivera, partial responder)
  data/genomes/patient_b.txt   (PT-002 — Jordan Kim, non-responder)
  data/genomes/patient_c.txt   (PT-003 — Morgan Chen, safety flags)

Usage:
  python scripts/build_patient_file.py

Owner: <unassigned>
"""

from __future__ import annotations

from pathlib import Path


GENOME_DIR = Path(__file__).resolve().parent.parent / "data" / "genomes"

HEADER = """# This data file generated by GIRA demo seeder.
# Format mimics 23andMe raw export.
# rsid\tchromosome\tposition\tgenotype
"""

LOCI = {
    "rs7903146": ("10", "114758349"),
    "rs622342":  ("1",  "160142187"),
    "rs5219":    ("11", "17409572"),
    "rs1801282": ("3",  "12393125"),
    "rs757110":  ("11", "17415608"),
    "rs9939609": ("16", "53820527"),
    "rs4149056": ("12", "21331549"),
    "rs429358":  ("19", "45411941"),
    "rs4244285": ("10", "94781859"),
    "rs9923231": ("16", "31107689"),
}

PATIENTS = {
    "patient_a.txt": {
        "rs7903146": "CT", "rs622342": "AG", "rs5219": "CT", "rs1801282": "CG",
        "rs757110":  "AG", "rs9939609": "AT", "rs4149056": "TC", "rs429358":  "CT",
        "rs4244285": "GA", "rs9923231": "GA",
    },
    "patient_b.txt": {
        "rs7903146": "TT", "rs622342": "AA", "rs5219": "TT", "rs1801282": "CC",
        "rs757110":  "AA", "rs9939609": "AA", "rs4149056": "TC", "rs429358":  "CT",
        "rs4244285": "GA", "rs9923231": "GA",
    },
    "patient_c.txt": {
        "rs7903146": "CC", "rs622342": "AG", "rs5219": "CC", "rs1801282": "CG",
        "rs757110":  "AG", "rs9939609": "AT", "rs4149056": "TT", "rs429358":  "TT",
        "rs4244285": "AA", "rs9923231": "AA",
    },
}


def write_patient(filename: str, genotypes: dict) -> Path:
    GENOME_DIR.mkdir(parents=True, exist_ok=True)
    out = GENOME_DIR / filename
    lines = [HEADER.rstrip()]
    for rsid, gt in genotypes.items():
        chrom, pos = LOCI[rsid]
        lines.append(f"{rsid}\t{chrom}\t{pos}\t{gt}")
    out.write_text("\n".join(lines) + "\n")
    return out


def main() -> None:
    for fname, genotypes in PATIENTS.items():
        path = write_patient(fname, genotypes)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
