"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { ChevronDown, ChevronRight, ExternalLink } from "lucide-react"
import type { AgentBrief, Patient, SafetyFlag, TraceStep } from "@/lib/types"
import { formatTraceStep, genotypeForFlag, severityUi, toolConsoleLabel } from "@/lib/mappers"
import SnpDetailPanel from "./snp-detail-panel"

interface DoctorBriefViewProps {
  patient: Patient
  brief: AgentBrief
  safetyFlags: SafetyFlag[]
  snpProfile: Record<string, { genotype?: string }>
}

function truncateTitle(title: string, max = 60): string {
  const t = title.trim()
  if (t.length <= max) return t
  return t.slice(0, max - 1) + "…"
}

export default function DoctorBriefView({
  patient,
  brief,
  safetyFlags,
  snpProfile,
}: DoctorBriefViewProps) {
  const [expandedSnp, setExpandedSnp] = useState<string | null>(null)
  const [traceOpen, setTraceOpen] = useState(false)
  const [panelGene, setPanelGene] = useState<{
    gene: string
    rsid?: string
    genotype?: string
  } | null>(null)

  const displayFlags = brief.safety_flags?.length
    ? brief.safety_flags.map((f) => ({
        gene: f.gene || "",
        rsid: f.rsid || "",
        genotype: genotypeForFlag(f, snpProfile),
        severity: severityUi(f.severity),
        description: f.flag || "",
        action: f.action || "",
        pmid: f.pmid,
        prescribed: f.currently_prescribed,
      }))
    : safetyFlags.map((f) => ({
        gene: f.gene,
        rsid: f.rsid,
        genotype: f.risk_genotype || genotypeForFlag(f, snpProfile),
        severity: severityUi(f.severity),
        description: f.flag,
        action: f.action,
        pmid: f.pmid,
        prescribed: f.currently_prescribed,
      }))

  const critical = displayFlags.find((f) => f.severity === "critical")
  const rec = brief.recommendation
  const snpRows = brief.snp_summary || []
  const trials = brief.trial_matches || []
  const citations = (brief.citations || []).filter((c) => c.pmid && (c.title || "").trim())

  const wearable = brief.wearable_insight as Record<string, unknown> | undefined
  const glucose = brief.glucose_insight as Record<string, unknown> | undefined

  const backendLabel = brief._backend || "deterministic"

  return (
    <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
      <header className="border border-[#E8E6F0] rounded-lg bg-white p-5">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <h2 className="text-[22px] font-semibold text-[#0D0B14]">{patient.name}</h2>
            <p className="font-mono text-[13px] text-[#9895A8] mt-1">{patient.id}</p>
            <p className="text-[14px] text-[#6B6778] mt-2">{patient.appointment}</p>
          </div>
          <div className="text-right">
            <p className="text-[12px] text-[#9895A8]">Generated by GIRA Agent</p>
            <p className="text-[13px] font-mono text-[#5B3FD4]">{backendLabel}</p>
            <p className="text-[12px] text-[#9895A8] mt-1">
              {brief.generated_at ? new Date(brief.generated_at).toLocaleString() : "—"}
            </p>
            {brief.cached && (
              <span className="inline-block mt-2 px-2 py-0.5 text-[11px] font-semibold uppercase bg-[#F0EEF5] text-[#5B3FD4] rounded">
                Cached
              </span>
            )}
          </div>
        </div>
      </header>

      {displayFlags.some((f) => f.severity === "critical") && (
        <div className="w-full bg-[#C0392B] text-white rounded-lg px-5 py-4">
          <p className="text-[13px] font-bold uppercase tracking-wide">Action required before appointment:</p>
          <p className="text-[15px] mt-1 font-medium">
            {critical?.description || displayFlags[0]?.description}
          </p>
        </div>
      )}

      <section className="space-y-3">
        <p className="text-[11px] font-semibold uppercase text-[#9895A8]">Safety flags</p>
        {displayFlags.length === 0 ? (
          <p className="text-[13px] text-[#9895A8]">No flags.</p>
        ) : (
          displayFlags.map((flag) => (
            <div
              key={`${flag.gene}-${flag.rsid}`}
              className="border border-[#E8E6F0] rounded-lg bg-white p-4"
            >
              <div className="flex flex-wrap items-center justify-between gap-2 mb-2">
                <span className="font-mono font-bold text-[#0D0B14]">
                  {flag.gene} {flag.rsid} {flag.genotype}
                </span>
                <span
                  className={`text-[11px] font-bold uppercase px-2 py-0.5 rounded ${
                    flag.severity === "critical"
                      ? "bg-[#FDECEC] text-[#C0392B]"
                      : "bg-[#FFF8EB] text-[#B45309]"
                  }`}
                >
                  {flag.severity === "critical" ? "Critical" : "Warning"}
                </span>
              </div>
              <p className="text-[13px] text-[#6B6778]">{flag.description}</p>
              <p className="text-[13px] text-[#0D0B14] mt-2">{flag.action}</p>
              {flag.pmid && (
                <a
                  href={`https://pubmed.ncbi.nlm.nih.gov/${flag.pmid}/`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[12px] text-[#5B3FD4] mt-2 inline-flex items-center gap-1"
                >
                  PMID {flag.pmid} <ExternalLink className="w-3 h-3" />
                </a>
              )}
              <p className="text-[12px] text-[#9895A8] mt-2">
                Currently prescribed: {flag.prescribed ? "Yes" : "No"}
              </p>
            </div>
          ))
        )}
      </section>

      {snpRows.length > 0 && (
        <section className="border border-[#E8E6F0] rounded-lg bg-white overflow-hidden">
          <p className="px-5 py-3 text-[11px] font-semibold uppercase text-[#9895A8] border-b border-[#E8E6F0]">
            SNP summary
          </p>
          <div className="divide-y divide-[#E8E6F0]">
            {snpRows.map((snp) => {
              const key = snp.rsid || snp.gene || ""
              const open = expandedSnp === key
              return (
                <div key={key}>
                  <button
                    type="button"
                    onClick={() => {
                      setExpandedSnp(open ? null : key)
                      if (snp.gene) setPanelGene({ gene: snp.gene, rsid: snp.rsid, genotype: snp.genotype })
                    }}
                    className="w-full px-5 py-3 flex items-center justify-between text-left hover:bg-[#FAFAFC]"
                  >
                    <span className="font-mono text-[13px] font-semibold">
                      {snp.gene} · {snp.rsid} · {snp.genotype}
                    </span>
                    {open ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
                  </button>
                  {open && (
                    <div className="px-5 pb-4 text-[13px] text-[#6B6778] space-y-2">
                      <p>{snp.finding}</p>
                      <p>
                        Evidence: <span className="font-medium">{snp.evidence_level || "—"}</span>
                      </p>
                      {snp.rsid && (
                        <a
                          href={`https://www.ncbi.nlm.nih.gov/clinvar/?term=${snp.rsid}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-[#5B3FD4] inline-flex items-center gap-1"
                        >
                          ClinVar <ExternalLink className="w-3 h-3" />
                        </a>
                      )}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </section>
      )}

      <section>
        <p className="text-[11px] font-semibold uppercase text-[#9895A8] mb-3">Recommendations</p>
        <div className="grid md:grid-cols-3 gap-3">
          {rec?.discontinue && (
            <div className="border-l-[3px] border-l-[#C0392B] border border-[#E8E6F0] rounded-lg p-4 bg-white">
              <p className="text-[11px] font-bold uppercase text-[#C0392B]">Discontinue</p>
              <p className="text-[16px] font-semibold mt-1">{rec.discontinue}</p>
              <p className="text-[12px] text-[#6B6778] mt-2">{rec.rationale?.[0]}</p>
            </div>
          )}
          {rec?.start && (
            <div className="border-l-[3px] border-l-[#1A9E6E] border border-[#E8E6F0] rounded-lg p-4 bg-white">
              <p className="text-[11px] font-bold uppercase text-[#1A9E6E]">Start</p>
              <p className="text-[16px] font-semibold mt-1">{rec.start}</p>
              <p className="text-[12px] text-[#6B6778] mt-2">{rec.rationale?.[1] || rec.rationale?.[0]}</p>
            </div>
          )}
          {(rec?.rationale || []).slice(0, 2).map((r, i) => (
            <div
              key={i}
              className="border-l-[3px] border-l-[#5B3FD4] border border-[#E8E6F0] rounded-lg p-4 bg-white"
            >
              <p className="text-[11px] font-bold uppercase text-[#5B3FD4]">Consider</p>
              <p className="text-[13px] text-[#6B6778] mt-2">{r}</p>
            </div>
          ))}
        </div>
      </section>

      {(wearable || glucose) && (
        <section className="border border-[#E8E6F0] rounded-lg p-5 bg-white space-y-4">
          <p className="text-[11px] font-semibold uppercase text-[#9895A8]">WHOOP + glucose (30-day)</p>
          <div className="flex flex-wrap gap-2">
            {[
              { label: "HRV", val: (wearable as { hrv_avg?: number })?.hrv_avg },
              { label: "RHR", val: (wearable as { rhr_avg?: number })?.rhr_avg },
              { label: "Recovery", val: (wearable as { recovery_avg?: number })?.recovery_avg },
              { label: "TIR", val: (glucose as { time_in_range_pct?: number })?.time_in_range_pct },
              { label: "GMI", val: (glucose as { gmi?: number })?.gmi },
            ].map((chip) => (
              <span
                key={chip.label}
                className="px-3 py-1.5 bg-[#F9F8FC] border border-[#E8E6F0] rounded-full text-[12px] font-mono"
              >
                {chip.label}: {chip.val != null ? chip.val : "—"}
              </span>
            ))}
          </div>
          {Boolean(wearable?.summary || glucose?.summary) && (
            <p className="text-[13px] text-[#6B6778] leading-relaxed">
              {String(wearable?.summary || glucose?.summary || "")}
            </p>
          )}
        </section>
      )}

      {trials.length > 0 && (
        <section className="space-y-3">
          <p className="text-[11px] font-semibold uppercase text-[#9895A8]">Trial matches</p>
          {trials.map((t) => (
            <div
              key={t.nct_id || t.title}
              className="border-l-[3px] border-l-[#5B3FD4] border border-[#E8E6F0] rounded-lg p-4 bg-white"
            >
              <p className="font-mono text-[12px] text-[#5B3FD4]">{t.nct_id}</p>
              <p className="text-[15px] font-semibold mt-1">{t.title}</p>
              <p className="text-[13px] text-[#6B6778] mt-1">
                {[t.location, t.phase, "Recruiting"].filter(Boolean).join(" · ")}
              </p>
              <a
                href={t.url || `https://clinicaltrials.gov/study/${t.nct_id}`}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[13px] text-[#5B3FD4] mt-2 inline-flex items-center gap-1"
              >
                clinicaltrials.gov <ExternalLink className="w-3 h-3" />
              </a>
            </div>
          ))}
        </section>
      )}

      <section className="border border-[#E8E6F0] rounded-lg p-4 bg-white">
        <p className="text-[11px] font-semibold uppercase text-[#9895A8] mb-3">Citations (PubMed only)</p>
        {citations.length === 0 ? (
          <p className="text-[13px] text-[#9895A8]">No PubMed citations in this brief.</p>
        ) : (
          <ul className="space-y-2">
            {citations.map((c) => (
              <li key={c.pmid} className="text-[13px]">
                <a
                  href={c.url || `https://pubmed.ncbi.nlm.nih.gov/${c.pmid}/`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[#5B3FD4] font-mono font-medium"
                >
                  PMID:{c.pmid}
                </a>
                <span className="text-[#6B6778]"> — {truncateTitle(c.title || "")}</span>
                {(c as { gene?: string; drug?: string }).gene && (
                  <span className="text-[#9895A8]">
                    {" "}
                    — {(c as { gene?: string }).gene} + {(c as { drug?: string }).drug}
                  </span>
                )}
              </li>
            ))}
          </ul>
        )}
      </section>

      {brief._trace && brief._trace.length > 0 && (
        <section className="border border-[#E8E6F0] rounded-lg bg-white overflow-hidden">
          <button
            type="button"
            onClick={() => setTraceOpen((v) => !v)}
            className="w-full px-5 py-3 flex items-center justify-between text-left"
          >
            <span className="text-[11px] font-semibold uppercase text-[#9895A8]">GIRA Agent trace</span>
            {traceOpen ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
          </button>
          {traceOpen && (
            <div className="divide-y divide-[#E8E6F0] max-h-80 overflow-y-auto">
              {brief._trace.map((step: TraceStep, i) => (
                <div key={i} className="px-5 py-3 flex gap-3">
                  <span
                    className={`w-2 h-2 rounded-full mt-1.5 shrink-0 ${
                      step.status === "error"
                        ? "bg-[#EF4444]"
                        : step.status === "partial"
                          ? "bg-[#F59E0B]"
                          : "bg-[#1A9E6E]"
                    }`}
                  />
                  <div>
                    <p className="text-[13px] font-medium text-[#0D0B14]">{toolConsoleLabel(step.tool)}</p>
                    <p className="text-[12px] text-[#9895A8] font-mono">
                      {JSON.stringify(step.args_summary || {}).slice(0, 120)}
                    </p>
                    <p className="text-[12px] text-[#6B6778] mt-1">{formatTraceStep(step)}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>
      )}

      {panelGene && (
        <SnpDetailPanel
          gene={panelGene.gene}
          rsid={panelGene.rsid}
          genotype={panelGene.genotype}
          onClose={() => setPanelGene(null)}
        />
      )}
    </motion.div>
  )
}
